"""add asin release_date extra_description

Revision ID: 9b793042b934
Revises: bdedeca4d1be
Create Date: 2026-04-10 08:01:32.556527

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.migration_guards import add_column_if_missing

# revision identifiers, used by Alembic.
revision: str = "9b793042b934"
down_revision: str | Sequence[str] | None = "bdedeca4d1be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    add_column_if_missing("disc_jobs", sa.Column("asin", sa.String(), nullable=True))
    add_column_if_missing("disc_jobs", sa.Column("release_date", sa.String(), nullable=True))

    add_column_if_missing("disc_titles", sa.Column("extra_description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("disc_titles", schema=None) as batch_op:
        batch_op.drop_column("extra_description")

    with op.batch_alter_table("disc_jobs", schema=None) as batch_op:
        batch_op.drop_column("release_date")
        batch_op.drop_column("asin")

    # ### end Alembic commands ###
