"""add discdb wave2 columns

Revision ID: bdedeca4d1be
Revises: d9cbecac097c
Create Date: 2026-04-09 19:32:17.442150

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdedeca4d1be"
down_revision: str | Sequence[str] | None = "d9cbecac097c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("disc_titles", schema=None) as batch_op:
        batch_op.alter_column(
            "discdb_flagged",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("disc_titles", schema=None) as batch_op:
        batch_op.alter_column(
            "discdb_flagged",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    # ### end Alembic commands ###
